name: Android CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      arch-target: aarch64
      target: ${{ env.arch-target }}-linux-android
      binstall-args: --no-confirm --no-symlinks
      cache-name: ${{ runner.os }}-${{ runner.arch }}-${{ runner.name }}-cache-${{ env.target }}
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        key: ${{ env.cache-name }}
        path: |
          ~/.m2
          ~/.cargo
          ~/.gradle
          ~/.rustup
          ~/work
          ~/app
          !~/app/.*
          !~/app/*.*
          !~/app/src
          !~/app/rs/src
          !~/app/rs/.*
          !~/app/rs/*.*
          ~/app/lint-baseline.xml
    - name: Cargo Setup toolchain action ${{ env.arch }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ env.target }}
        override: true
        default: true
    - name: Rustup add ${{ env.target }} and Cargo install cargo-binstall
      run: |
        rustup target add ${{ env.target }}
        cargo install cargo-binstall
    - name: Cargo binstall cargo-update cross cargo-ndk cargo-xdk
      run: cargo binstall ${{ env.binstall-args }} cargo-update cross cargo-ndk cargo-xdk 
    #- name: Cargo Setup ${{ env.arch-target }}
      #uses: actions-rs/cargo@v1
      #with:
         #use-cross: true
         #command: 
         #args: --target ${{ env.target }} 
    - name: Cargo Update
      continue-on-error: true
      run: cargo update && cargo install-update -a && cargo cargo-update
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradlew check cargo
      run: ./gradlew cargoBuild
    - name: Build with Gradle
      continue-on-error: true
      run: ./gradlew build
    - name: Build Artifacts Twoyi-release.apk
      uses: actions/upload-artifact@v3
      with:
        path: ~/
    #- name: Build Artifacts Twoyi-debug.apk
      #uses: actions/upload-artifact@v3
      #with:
        #path: ~/app/build/outputs/apk/debug/*.apk
