name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  target: aarch64-linux-android
  binstall-args: --no-confirm --no-symlinks
  cache-name: cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        key: ${{ env.cache-name }}-${{ runner.os }}-${{ runner.arch }}-${{ github.job }}-${{ env.target }}
        path: |
          ~/work
          !~/work/.*
          !~/work/*.*
          !~/work/assets
          !~/work/app/.*
          !~/work/app/*.*
          !~/work/app/src
          !~/work/app/rs/src
          !~/work/app/rs/.*
          !~/work/app/rs/*.*
          ./
          !./.*
          !./*.*
          !./assets
          !./app/.*
          !./app/*.*
          !./app/src
          !./app/rs/src
          !./app/rs/.*
          !./app/rs/*.*
          ~/work/app/lint-baseline.xml
          ~/work/app/src/main/assets/rootfs.7z
          ~/work/.m2
          ~/work/.cargo
          ~/work/.gradle
          ~/work/.rustup
          ./app/lint-baseline.xml
          ./app/src/main/assets/rootfs.7z
          ./.m2
          ./.cargo
          ./.gradle
          ./.rustup
          ~/.m2
          ~/.cargo
          ~/.gradle
          ~/.rustup
    - name: Download Rootfs from lastest Twoyi.apk release
      shell: bash {0}
      run: |
        [ -f ./app/src/main/assets/rootfs.7z ] && exit 0
        mkdir extracted-apk
        cd extracted-apk
        curl -s https://api.github.com/repos/twoyi/twoyi/releases/latest | grep "browser_download_url.*\.apk" | cut -d : -f 2,3 | tr -d \" | wget -qi -
        unzip *.apk
        [ ! -d ../app/src/main/assets/ ] && mkdir -p ../app/src/main/assets/
        mv assets/* ../app/src/main/assets/
        cd -
        rm -rf extracted-apk
    - name: Update Grandle JVM Memory
      shell: bash {0}
      run: |
        free | head -n-1 | tail -n-1 | xargs -r | cut -d' ' -f4 | xargs bash -c 'echo MEMTOTAL=$0' >> $GITHUB_ENV
        . $GITHUB_ENV
        sed -i "s/$org\.gradle\.jvmargs=-Xmx2048m/org.gradle.jvmargs=-Xmx${MEMTOTAL}k/g" ./gradle.properties
        echo  "./gradle.properties updated:"
        grep 'org.gradle.jvmargs=' ./gradle.properties
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Cargo Setup toolchain action to ${{ env.target }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: ${{ env.target }}
        override: true
    - name: Rustup add ${{ env.target }} and Cargo install cargo-binstall
      shell: bash {0}
      run: |
        rustup target add ${{ env.target }}
        [ -f $HOME/.cargo/bin/cargo-binstall ] && exit 0
        wget -q https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
        [ ! -d $HOME/.cargo/bin ] && mkdir -p $HOME/.cargo/bin
        tar -xf cargo-binstall-x86_64-unknown-linux-musl.tgz -C $HOME/.cargo/bin
        rm cargo-binstall-x86_64-unknown-linux-musl.tgz
        #cargo install cargo-binstall
    - name: Cargo binstall cargo-update cross cargo-ndk cargo-xdk
      run: cargo binstall ${{ env.binstall-args }} cargo-update cross cargo-ndk cargo-xdk 
    #- name: Cargo Setup to ${{ env.target }}
      #uses: actions-rs/cargo@v1
      #with:
         #use-cross: true
         #command: 
         #args: --target ${{ env.target }} 
    - name: Cargo Update
      continue-on-error: true
      run: cargo install-update -a
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    #- name: Gradlew check cargo
      #run: ./gradlew cargoBuild
    - name: Build with Gradle
      continue-on-error: true
      run: |
        ./gradlew build
        ./gradlew assembleRelease -Prust-target=arm64
        ./gradlew assembleDebug -Prust-target=arm64
    - name: Build Artifacts Twoyi-release.apk
      uses: actions/upload-artifact@v3
      with:
        path: ./app/build/outputs/apk/release/*.apk
    - name: Build Artifacts Twoyi-debug.apk
      uses: actions/upload-artifact@v3
      with:
        path: ./app/build/outputs/apk/debug/*.apk
