name: Android CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      id: cache
      uses: actions/cache@v3
      env:
        cache-name: cache
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        path: |
            ~/.m2
            ~/.cargo
            ~/.gradle
            ~/.rustup
            ~/work
            ~/app
            !~/app/.*
            !~/app/*.*
            ~/app/lint-baseline.xml
            !~/app/src
            !~/app/rs/src
            !~/app/rs/.*
            !~/app/rs/*.*
    - name: Cargo install toolchain aarch64
      uses: actions-rs/toolchain@v1
      continue-on-error: true
      with:
        toolchain: nightly
        target: aarch64-linux-android
    - name: Cargo install xdk
      continue-on-error: true
      run: cargo install cargo-xdk
    - name: Cargo Setup aarch64
      run: rustup target add aarch64-linux-android
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradlew check cargo
      continue-on-error: true
      run: ./gradlew cargoBuild
    - name: Build with Gradle
      continue-on-error: true
      run: ./gradlew build
    - name: Build Artifacts Twoyi-release.apk
      uses: actions/upload-artifact@v3
      with:
        path: ~/app/build/outputs/apk/release/*.apk
    - name: Build Artifacts Twoyi-debug.apk
      uses: actions/upload-artifact@v3
      with:
        path: ~/app/build/outputs/apk/debug/*.apk
