name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      id: cache
      uses: actions/cache@v3
      env:
        cache-name: cache
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        path: |
            ~/.m2
            ~/.cargo
            ~/.gradle
            ~/.rustup
    - name: Cargo install toolchains
      uses: actions-rs/toolchain@v1
      #continue-on-error: true
      with:
        toolchain: nightly
        target: aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
        override: true
    - name: Cargo install xdk
      continue-on-error: true
      run: cargo install cargo-xdk
    - name: Cargo Setup
      continue-on-error: true
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradlew check cargo
      continue-on-error: true
      run: ./gradlew cargoBuild
    - name: Build with Gradle
      continue-on-error: true
      run: ./gradlew build --stacktrace --debug --scan
    - name: Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        path: .
